In [1]:
import geopandas as gpd
import numpy as np
import os
import pandas as pd

In [24]:
base_path = '/work/hawkins_lab/vulcan/data/vulcan'

res_par_file = os.path.join(base_path,'parquet','vulcan_RES_epa_climate.parquet')
com_par_file = os.path.join(base_path,'parquet','vulcan_COM_epa_climate.parquet')
ind_par_file = os.path.join(base_path,'parquet','vulcan_IND_epa_climate.parquet')
tran_par_file = os.path.join(base_path,'parquet','vulcan_ONR_epa_climate.parquet')
elec_par_file = os.path.join(base_path,'parquet','vulcan_SC2_epa_climate.parquet')
tot_par_file = os.path.join(base_path,'parquet','vulcan_TOT_epa_climate.parquet')

epa = gpd.read_file("/work/hawkins_lab/vulcan/data/gis/epa-sld/smartlocationdb_4326.shp", engine="pyogrio", use_arrow=True)
# Convert all column names to lowercase
epa.columns = epa.columns.str.lower()
epa.geoid20 = epa.geoid20.astype(int)

In [16]:
cols = ['value_weig',
 'p_wrkage',
 'pct_ao0',
 'pct_ao1',
 'pct_ao2p',
 'r_pctlowwa',
 'totemp',
 'totpop',
 'e5_ret',
 'e5_off',
 'e5_ind',
 'e5_svc',
 'e5_ent',
 'e8_ret',
 'e8_off',
 'e8_ind',
 'e8_svc',
 'e8_ent',
 'e8_ed',
 'e8_hlth',
 'e8_pub',
 'e_pctlowwa',
 'd1a',
 'd1b',
 'd1c',
 'd1c5_ret',
 'd1c5_off',
 'd1c5_ind',
 'd1c5_svc',
 'd1c5_ent',
 'd1c8_ret',
 'd1c8_off',
 'd1c8_ind',
 'd1c8_svc',
 'd1c8_ent',
 'd1c8_ed',
 'd1c8_hlth',
 'd1c8_pub',
 'd1d',
 'd2a_jphh',
 'd2b_e5mix',
 'd2b_e5mixa',
 'd2b_e8mix',
 'd2b_e8mixa',
 'd2a_ephhm',
 'd2c_trpmx1',
 'd2c_trpmx2',
 'd2c_tripeq',
 'd2r_jobpop',
 'd2r_wrkemp',
 'd2a_wrkemp',
 'd2c_wremlx',
 'd3a',
 'd3aao',
 'd3amm',
 'd3apo',
 'd3b',
 'd3bao',
 'd3bmm3',
 'd3bmm4',
 'd3bpo3',
 'd3bpo4',
 'd4a',
 'd4b025',
 'd4b050',
 'd4c',
 'd4d',
 'd4e',
 'd5ar',
 'd5ae',
 'd5br',
 'd5be',
 'd5cr',
 'd5cri',
 'd5ce',
 'd5cei',
 'd5dr',
 'd5dri',
 'd5de',
 'd5dei',
 'd2a_ranked',
 'd2b_ranked',
 'd3b_ranked',
 'd4a_ranked',
 'natwalkind',
 'w_p_lowwag',
 'w_p_medwag',
 'w_p_highwa',
 'gasprice',
 'c_r_white',
 'c_r_male',
 'c_r_lowwag',
 'c_r_medwag',
 'c_r_highwa',
 'c_r_drmv',
 'p_highschool',
 'p_owner',
 'avg_hh_size',
 'med_dwelling_age',
 'noncom_vmt', 
 'com_vmt_pe',
 'vmt_per_wo',
 'vmt_tot_mi',
 'vmt_tot_ma', 
 'vmt_tot_av',
 'ghg_per_wo',
 'annual_ghg'
]

rows_keep = ['value_weig',
 'd1a',
 'd1b',
 'd1c',
 'd1c5_ret',
 'd1c5_off',
 'd1c5_ind',
 'd1c5_svc',
 'd1c5_ent',
 'd1c8_ret',
 'd1c8_off',
 'd1c8_ind',
 'd1c8_svc',
 'd1c8_ent',
 'd1c8_ed',
 'd1c8_hlth',
 'd1c8_pub',
 'd1d',
 'd2a_jphh',
 'd2b_e5mix',
 'd2b_e5mixa',
 'd2b_e8mix',
 'd2b_e8mixa',
 'd2a_ephhm',
 'd2c_trpmx1',
 'd2c_trpmx2',
 'd2c_tripeq',
 'd2r_jobpop',
 'd2r_wrkemp',
 'd2a_wrkemp',
 'd2c_wremlx',
 'd3a',
 'd3aao',
 'd3amm',
 'd3apo',
 'd3b',
 'd3bao',
 'd3bmm3',
 'd3bmm4',
 'd3bpo3',
 'd3bpo4',
 'd4a',
 'd4b025',
 'd4b050',
 'd4c',
 'd4d',
 'd4e',
 'd5ar',
 'd5ae',
 'd5br',
 'd5be',
 'd5cr',
 'd5cri',
 'd5ce',
 'd5cei',
 'd5dr',
 'd5dri',
 'd5de',
 'd5dei',
 'd2a_ranked',
 'd2b_ranked',
 'd3b_ranked',
 'd4a_ranked',
 'natwalkind',
 'noncom_vmt', 
 'com_vmt_pe',
 'vmt_per_wo',
 'vmt_tot_mi',
 'vmt_tot_ma', 
 'vmt_tot_av',
 'ghg_per_wo',
 'annual_ghg'
]
cols_keep = ['p_wrkage',
 'pct_ao0',
 'pct_ao1',
 'pct_ao2p',
 'r_pctlowwa',
 'totemp',
 'totpop',
 'e5_ret',
 'e5_off',
 'e5_ind',
 'e5_svc',
 'e5_ent',
 'e8_ret',
 'e8_off',
 'e8_ind',
 'e8_svc',
 'e8_ent',
 'e8_ed',
 'e8_hlth',
 'e8_pub',
 'e_pctlowwa',
 'w_p_lowwag',
 'w_p_medwag',
 'w_p_highwa',
 'gasprice',
 'c_r_white',
 'c_r_male',
 'c_r_lowwag',
 'c_r_medwag',
 'c_r_highwa',
 'c_r_drmv',
 'p_highschool',
 'p_owner',
 'avg_hh_size',
 'med_dwelling_age',
 'noncom_vmt', 
 'com_vmt_pe',
 'vmt_per_wo',
 'vmt_tot_mi',
 'vmt_tot_ma', 
 'vmt_tot_av',
 'ghg_per_wo',
 'annual_ghg'
 # 'precip_201401',
 # 'precip_201407',
 # 'min_temp_201401',
 # 'min_temp_201407',
 # 'mean_temp_201401',
 # 'mean_temp_201407',
 # 'max_temp_201401',
 # 'max_temp_201407',
 # 'stc2erta'
]

## Transportation

In [26]:
df

,geoid20,value_weig,objectid,geoid10,statefp,countyfp,tractce,blkgrpce,csa,csa_name,...,avg_hh_size,med_dwelling_age,noncom_vmt_y,com_vmt_pe_y,vmt_per_wo_y,vmt_tot_mi_y,vmt_tot_ma_y,vmt_tot_av_y,ghg_per_wo_y,annual_ghg_y
0,10010201001,5355.473125,23851.0,010010201001,01,001,020100,1,388,"Montgomery-Selma-Alexander City, AL",...,2.16,43.0,8.446433,19.888146,28.334579,15.983669,39.918925,26.122786,25.246110,6563.988587
1,10010201002,3610.348786,21583.0,010010201002,01,001,020100,2,388,"Montgomery-Selma-Alexander City, AL",...,2.73,31.0,8.004397,19.858846,27.863243,15.983669,39.918925,26.122786,24.826149,6454.798843
2,10010202001,2342.722381,21598.0,010010202001,01,001,020200,1,388,"Montgomery-Selma-Alexander City, AL",...,2.52,41.0,6.247714,17.648428,23.896143,15.983669,39.918925,26.122786,21.291463,5535.780381
3,10010202002,2658.792416,21599.0,010010202002,01,001,020200,2,388,"Montgomery-Selma-Alexander City, AL",...,2.56,47.0,4.734573,15.660024,20.394596,15.983669,39.918925,26.122786,18.171585,4724.612177
4,10010203001,5637.626596,21662.0,010010203001,01,001,020300,1,388,"Montgomery-Selma-Alexander City, AL",...,2.79,39.0,6.603140,18.942404,25.545544,15.983669,39.918925,26.122786,22.761080,5917.880799
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216285,560459511001,14530.009742,217582.0,560459511001,56,045,951100,1,None,None,...,2.09,38.0,8.550445,10.237426,18.787871,13.218230,33.315561,21.046887,16.739993,4352.398082
216286,560459511002,30198.379005,217583.0,560459511002,56,045,951100,2,None,None,...,2.13,27.0,8.695474,10.842813,19.538287,13.218230,33.315561,21.046887,17.408614,4526.239577
216287,560459513001,1565.716626,217585.0,560459513001,56,045,951300,1,None,None,...,2.29,53.0,7.656297,9.936737,17.593034,13.218230,33.315561,21.046887,15.675393,4075.602307
216288,560459513002,1696.773582,217586.0,560459513002,56,045,951300,2,None,None,...,2.04,58.0,6.752922,9.258402,16.011324,13.218230,33.315561,21.046887,14.266090,3709.183336
216289,560459513003,3234.323517,217584.0,560459513003,56,045,951300,3,None,None,...,2.50,37.0,7.959737,9.541460,17.501197,13.218230,33.315561,21.046887,15.593566,4054.327272

In [33]:
df = gpd.read_parquet(tran_par_file)

if set(rows_keep).difference(df.columns):
    df = pd.merge(
        df,
        epa[['geoid20','noncom_vmt', 'com_vmt_pe', 'vmt_per_wo', 'vmt_tot_mi',
     'vmt_tot_ma', 'vmt_tot_av', 'ghg_per_wo', 'annual_ghg']], # Select only the columns you need from the second DF
        on='geoid20',
        how='left'
    )
df.to_parquet(tran_par_file)
df[rows_keep] = df.loc[:, rows_keep].replace(0, 1)
df.loc[:,rows_keep] = np.log(df.loc[:,rows_keep])
correlation_table = df.loc[:, cols].corr()
correlation_table = correlation_table.loc[rows_keep, cols_keep]
correlation_table.to_csv("/work/hawkins_lab/vulcan/results/correlation_table_transport.csv")
print(correlation_table)

/global/software/python/3.12.5/lib/python3.12/site-packages/pandas/core/internals/blocks.py:366: RuntimeWarning: invalid value encountered in log
  result = func(self.values, **kwargs)

            p_wrkage   pct_ao0   pct_ao1  pct_ao2p  r_pctlowwa    totemp  \
value_weig -0.043642 -0.250102 -0.154157  0.276145   -0.050686  0.234312
d1a         0.196267  0.398043  0.331727 -0.475604   -0.082965  0.012112
d1b         0.205420  0.369825  0.277636 -0.415934   -0.095603  0.008115
d1c         0.183238  0.353281  0.311800 -0.448829   -0.087551  0.291162
d1c5_ret    0.113447  0.231883  0.198109 -0.299680   -0.058976  0.095519
...              ...       ...       ...       ...         ...       ...
vmt_tot_mi -0.119325 -0.284760 -0.013111  0.197476    0.311025 -0.023763
vmt_tot_ma  0.083466 -0.040271 -0.033330  0.051619   -0.197864  0.031322
vmt_tot_av -0.080862 -0.277713 -0.015090  0.197504    0.226322 -0.017496
ghg_per_wo -0.187763 -0.533222 -0.218713  0.475453    0.091121 -0.068958
annual_ghg -0.187763 -0.533222 -0.218713  0.475453    0.091121 -0.068958

              totpop    e5_ret    e5_off    e5_ind  ...  avg_hh_size  \
value_weig  0.298243  0.228904  0.098524  0.249815  ...    -0.002758
d1a         0.036436  0.017332  0.029686 -0.089334  ...     0.015290
d1b         0.091297  0.012251  0.022411 -0.087333  ...     0.123286
d1c         0.029901  0.237893  0.165293  0.133041  ...    -0.041683
d1c5_ret   -0.092891  0.202159  0.060362 -0.009607  ...    -0.001173
...              ...       ...       ...       ...  ...          ...
vmt_tot_mi -0.019725 -0.008580 -0.020479  0.012110  ...    -0.139909
vmt_tot_ma  0.109784  0.017081  0.016414  0.011143  ...     0.161110
vmt_tot_av -0.005610 -0.007583 -0.017181  0.012195  ...    -0.144478
ghg_per_wo  0.051425 -0.040337 -0.069429  0.055568  ...     0.025314
annual_ghg  0.051425 -0.040337 -0.069429  0.055568  ...     0.025314

            med_dwelling_age  noncom_vmt  com_vmt_pe  vmt_per_wo  vmt_tot_mi  \
value_weig         -0.296953    0.457302    0.355507    0.406436    0.230334
d1a                 0.222218   -0.838473   -0.590478   -0.697319   -0.475886
d1b                 0.212707   -0.829472   -0.577702   -0.684803   -0.491311
d1c                 0.187885   -0.773660   -0.500563   -0.607575   -0.397345
d1c5_ret            0.159262   -0.526165   -0.364958   -0.432624   -0.279240
...                      ...         ...         ...         ...         ...
vmt_tot_mi         -0.155505    0.586653    0.494141    0.547941    1.000000
vmt_tot_ma         -0.063065   -0.148479    0.116859    0.058755   -0.255752
vmt_tot_av         -0.170299    0.607172    0.636634    0.665389    0.734626
ghg_per_wo         -0.225921    0.823417    0.980469    1.000000    0.547941
annual_ghg         -0.225921    0.823417    0.980469    1.000000    0.547941

            vmt_tot_ma  vmt_tot_av  ghg_per_wo  annual_ghg
value_weig    0.017804    0.243438    0.406436    0.406436
d1a           0.185372   -0.479867   -0.697319   -0.697319
d1b           0.205218   -0.493619   -0.684803   -0.684803
d1c           0.151691   -0.403444   -0.607575   -0.607575
d1c5_ret      0.113244   -0.290709   -0.432624   -0.432624
...                ...         ...         ...         ...
vmt_tot_mi   -0.255752    0.734626    0.547941    0.547941
vmt_tot_ma    1.000000    0.159255    0.058755    0.058755
vmt_tot_av    0.159255    1.000000    0.665389    0.665389
ghg_per_wo    0.058755    0.665389    1.000000    1.000000
annual_ghg    0.058755    0.665389    1.000000    1.000000

[72 rows x 43 columns]

In [35]:
df.loc[:, rows_keep].describe()

,value_weig,d1a,d1b,d1c,d1c5_ret,d1c5_off,d1c5_ind,d1c5_svc,d1c5_ent,d1c8_ret,...,d4a_ranked,natwalkind,noncom_vmt,com_vmt_pe,vmt_per_wo,vmt_tot_mi,vmt_tot_ma,vmt_tot_av,ghg_per_wo,annual_ghg
count,216290.000000,216290.000000,216290.000000,216290.000000,216290.000000,216290.000000,216290.000000,216290.000000,216290.000000,216290.000000,...,216290.000000,216290.000000,216290.000000,216290.000000,216290.000000,216290.000000,216290.000000,216290.000000,216290.000000,216290.000000
mean,8.130287,0.059844,0.897151,-0.942323,-2.292976,-2.568086,-2.559597,-1.960160,-1.894419,-2.292976,...,1.209697,2.138672,1.514319,2.721217,2.996476,1.965966,3.783959,3.064651,2.881066,8.441747
std,1.200218,2.051234,2.098426,2.463440,2.633688,2.756220,2.301675,2.712460,2.543981,2.633688,...,1.387141,0.535521,0.548115,0.467018,0.454539,0.940084,0.374794,0.265960,0.454539,0.454539
min,-5.296206,-10.652923,-10.384659,-12.494022,-13.802673,-13.905222,-13.961359,-13.643936,-14.189734,-13.802673,...,0.000000,0.000000,-1.814998,-0.951491,0.031636,0.031636,2.799909,2.413897,-0.083775,5.476907
25%,7.331223,-1.141304,-0.295857,-2.358941,-3.901693,-4.312552,-4.052548,-3.454053,-3.291581,-3.901693,...,0.000000,1.791759,1.194743,2.526694,2.792332,1.458771,3.562125,2.910372,2.676921,8.237603
50%,8.112852,0.610512,1.462231,-0.527298,-1.641644,-2.152800,-2.439680,-1.468009,-0.953098,-1.641644,...,0.000000,2.215574,1.546269,2.780095,3.043571,2.336285,3.649986,3.077289,2.928160,8.488842
75%,8.915971,1.419829,2.309935,0.788806,0.000000,0.000000,-0.603428,0.000000,0.000000,0.000000,...,2.772589,2.590267,1.951282,3.009375,3.296250,2.600782,3.915707,3.249199,3.180839,8.741521
max,14.353681,7.300646,8.049931,9.549150,6.052659,9.251573,7.147409,9.525027,6.661514,6.052659,...,2.995732,2.995732,2.792468,4.958883,5.020322,3.833627,5.020322,3.988747,4.904911,10.465593

In [6]:
# df_cbsa = df.groupby('cbsa').agg(aggregation_functions)
# correlation_table = df_cbsa.corr()
# correlation_table = correlation_table.loc[rows_keep, cols_keep]
# correlation_table.to_csv("/work/hawkins_lab/vulcan/results/correlation_table_transportation_cbsa.csv")
# print(correlation_table)

## Residential

In [7]:
df = gpd.read_parquet(res_par_file)
cols_keep = ['p_wrkage',
 'pct_ao0',
 'pct_ao1',
 'pct_ao2p',
 'r_pctlowwa',
 'totemp',
 'totpop',
 'e5_ret',
 'e5_off',
 'e5_ind',
 'e5_svc',
 'e5_ent',
 'e8_ret',
 'e8_off',
 'e8_ind',
 'e8_svc',
 'e8_ent',
 'e8_ed',
 'e8_hlth',
 'e8_pub',
 'e_pctlowwa',
 'w_p_lowwag',
 'w_p_medwag',
 'w_p_highwa',
 'gasprice',
 'c_r_white',
 'c_r_male',
 'c_r_lowwag',
 'c_r_medwag',
 'c_r_highwa',
 'c_r_drmv',
 'p_highschool',
 'p_owner',
 'avg_hh_size',
 'med_dwelling_age'
]

In [8]:
df[rows_keep] = df.loc[:, rows_keep].replace(0, 1)
df.loc[:,rows_keep] = np.log(df.loc[:,rows_keep])

correlation_table = df.loc[:, cols].corr()
correlation_table = correlation_table.loc[rows_keep, cols_keep]
correlation_table.to_csv("/work/hawkins_lab/vulcan/results/correlation_table_res.csv")
print(correlation_table)

/global/software/python/3.12.5/lib/python3.12/site-packages/pandas/core/internals/blocks.py:366: RuntimeWarning: invalid value encountered in log
  result = func(self.values, **kwargs)

            p_wrkage   pct_ao0   pct_ao1  pct_ao2p  r_pctlowwa    totemp  \
value_weig  0.060496  0.006168 -0.131875  0.117532   -0.107017  0.082127
d1a         0.196354  0.398027  0.331764 -0.475661   -0.082955  0.012110
d1b         0.205505  0.369817  0.277701 -0.415942   -0.095596  0.008101
d1c         0.183246  0.353303  0.311888 -0.448834   -0.087534  0.291143
d1c5_ret    0.113592  0.231904  0.198132 -0.299704   -0.058988  0.095529
...              ...       ...       ...       ...         ...       ...
d2a_ranked  0.059926  0.015713  0.065560 -0.005386    0.027222  0.187803
d2b_ranked  0.089843 -0.037510  0.025543  0.065082   -0.098536  0.073960
d3b_ranked  0.180422  0.196007  0.325550 -0.310290    0.008312  0.053280
d4a_ranked  0.197515  0.330191  0.249377 -0.375758   -0.057183  0.061483
natwalkind  0.227383  0.307364  0.332876 -0.374875   -0.007615  0.118612

              totpop    e5_ret    e5_off    e5_ind  ...  c_r_white  c_r_male  \
value_weig  0.091213  0.070647  0.035964  0.078558  ...   0.187977 -0.002181
d1a         0.036417  0.017336  0.029698 -0.089347  ...  -0.454626 -0.281057
d1b         0.091254  0.012260  0.022374 -0.087339  ...  -0.479070 -0.272022
d1c         0.029868  0.237889  0.165258  0.133036  ...  -0.361873 -0.220842
d1c5_ret   -0.092829  0.202182  0.060357 -0.009596  ...  -0.273932 -0.156461
...              ...       ...       ...       ...  ...        ...       ...
d2a_ranked  0.001214  0.258826  0.091021  0.147286  ...   0.083390  0.050233
d2b_ranked  0.193630  0.173514  0.057177  0.001956  ...   0.066582  0.025547
d3b_ranked  0.008521  0.064980  0.040693 -0.051796  ...  -0.352242 -0.188555
d4a_ranked -0.065523  0.036889  0.050679 -0.013542  ...  -0.449796 -0.205210
natwalkind  0.000850  0.150628  0.079835 -0.004757  ...  -0.385722 -0.189445

            c_r_lowwag  c_r_medwag  c_r_highwa  c_r_drmv  p_highschool  \
value_weig   -0.105730   -0.373131    0.302060 -0.008535     -0.167435
d1a          -0.354253   -0.338177    0.373258  0.526265     -0.159385
d1b          -0.378692   -0.354441    0.394066  0.535338     -0.144751
d1c          -0.305596   -0.318374    0.340655  0.416575     -0.169994
d1c5_ret     -0.214480   -0.209745    0.229488  0.312409     -0.097463
...                ...         ...         ...       ...           ...
d2a_ranked    0.036666   -0.020728    0.000405 -0.093859     -0.043137
d2b_ranked   -0.051346   -0.081397    0.076785 -0.057983     -0.176916
d3b_ranked   -0.270445   -0.257943    0.284827  0.307471     -0.134070
d4a_ranked   -0.313622   -0.269653    0.309625  0.447397     -0.056731
natwalkind   -0.288982   -0.297969    0.319980  0.372611     -0.135120

             p_owner  avg_hh_size  med_dwelling_age
value_weig  0.118597    -0.052123          0.079897
d1a        -0.464196     0.015382          0.222192
d1b        -0.443757     0.123224          0.212662
d1c        -0.480856    -0.041503          0.187844
d1c5_ret   -0.295132    -0.001030          0.159328
...              ...          ...               ...
d2a_ranked -0.079943    -0.102729          0.020421
d2b_ranked -0.007130    -0.096547         -0.061075
d3b_ranked -0.349888     0.036049          0.250243
d4a_ranked -0.388163     0.061579          0.256812
natwalkind -0.429385    -0.003313          0.278138

[64 rows x 35 columns]

In [9]:
# df_cbsa = df.groupby('cbsa').agg(aggregation_functions)
# correlation_table = df_cbsa.corr()
# correlation_table = correlation_table.loc[rows_keep, cols_keep]
# correlation_table.to_csv("/work/hawkins_lab/vulcan/results/correlation_table_residential_cbsa.csv")
# print(correlation_table)

## Commercial

In [10]:
df = gpd.read_parquet(com_par_file)
df[rows_keep] = df.loc[:, rows_keep].replace(0, 1)
df.loc[:,rows_keep] = np.log(df.loc[:,rows_keep])

correlation_table = df.loc[:, cols].corr()
correlation_table = correlation_table.loc[rows_keep, cols_keep]
correlation_table.to_csv("/work/hawkins_lab/vulcan/results/correlation_table_commerce.csv")
print(correlation_table)

/global/software/python/3.12.5/lib/python3.12/site-packages/pandas/core/internals/blocks.py:366: RuntimeWarning: invalid value encountered in log
  result = func(self.values, **kwargs)

            p_wrkage   pct_ao0   pct_ao1  pct_ao2p  r_pctlowwa    totemp  \
value_weig  0.068905  0.111425  0.075411 -0.113682    0.017916  0.336468
d1a         0.196130  0.398256  0.331835 -0.475750   -0.082934  0.012084
d1b         0.205385  0.370040  0.277774 -0.416023   -0.095477  0.008090
d1c         0.182995  0.353348  0.311802 -0.448903   -0.087677  0.291169
d1c5_ret    0.113130  0.231846  0.198014 -0.299743   -0.059147  0.095524
...              ...       ...       ...       ...         ...       ...
d2a_ranked  0.060642  0.015846  0.065899 -0.004984    0.027749  0.187767
d2b_ranked  0.090440 -0.037371  0.025827  0.065460   -0.097935  0.073924
d3b_ranked  0.180672  0.196212  0.325782 -0.310005    0.008830  0.053247
d4a_ranked  0.197482  0.330259  0.249301 -0.375599   -0.057070  0.061511
natwalkind  0.227896  0.307615  0.333156 -0.374481   -0.006941  0.118611

              totpop    e5_ret    e5_off    e5_ind  ...  c_r_white  c_r_male  \
value_weig  0.144108  0.285112  0.170158  0.257370  ...   0.160276 -0.071953
d1a         0.036303  0.017306  0.029673 -0.089382  ...  -0.454646 -0.281006
d1b         0.091210  0.012227  0.022401 -0.087374  ...  -0.479091 -0.271935
d1c         0.029818  0.237901  0.165291  0.133028  ...  -0.361856 -0.220870
d1c5_ret   -0.092930  0.202170  0.060359 -0.009612  ...  -0.273819 -0.156568
...              ...       ...       ...       ...  ...        ...       ...
d2a_ranked  0.001231  0.258830  0.090869  0.147295  ...   0.083525  0.050391
d2b_ranked  0.193552  0.173510  0.057024  0.001982  ...   0.066759  0.025659
d3b_ranked  0.008470  0.064977  0.040579 -0.051791  ...  -0.352146 -0.188434
d4a_ranked -0.065473  0.036895  0.050724 -0.013540  ...  -0.449791 -0.205244
natwalkind  0.000862  0.150638  0.079778 -0.004747  ...  -0.385636 -0.189332

            c_r_lowwag  c_r_medwag  c_r_highwa  c_r_drmv  p_highschool  \
value_weig   -0.024031   -0.201580    0.150443  0.039828     -0.102561
d1a          -0.354196   -0.338026    0.373126  0.526106     -0.159314
d1b          -0.378576   -0.354274    0.393900  0.535170     -0.144674
d1c          -0.305607   -0.318335    0.340629  0.416442     -0.170046
d1c5_ret     -0.214504   -0.209788    0.229525  0.312342     -0.097562
...                ...         ...         ...       ...           ...
d2a_ranked    0.036825   -0.020616    0.000267 -0.094171     -0.042994
d2b_ranked   -0.051137   -0.081274    0.076619 -0.058342     -0.176765
d3b_ranked   -0.270256   -0.257721    0.284596  0.307125     -0.133937
d4a_ranked   -0.313615   -0.269636    0.309606  0.447181     -0.056747
natwalkind   -0.288811   -0.297795    0.319791  0.372205     -0.134962

             p_owner  avg_hh_size  med_dwelling_age
value_weig -0.106090    -0.164854          0.012818
d1a        -0.464177     0.015412          0.222172
d1b        -0.443763     0.123321          0.212659
d1c        -0.480774    -0.041596          0.187845
d1c5_ret   -0.295093    -0.001120          0.159279
...              ...          ...               ...
d2a_ranked -0.079822    -0.102559          0.020630
d2b_ranked -0.007024    -0.096309         -0.060872
d3b_ranked -0.349767     0.036278          0.250282
d4a_ranked -0.388089     0.061580          0.256793
natwalkind -0.429260    -0.003068          0.278258

[64 rows x 35 columns]

In [11]:
# df_cbsa = df.groupby('cbsa').agg(aggregation_functions)
# correlation_table = df_cbsa.corr()
# correlation_table = correlation_table.loc[rows_keep, cols_keep]
# correlation_table.to_csv("/work/hawkins_lab/vulcan/results/correlation_table_commerce_cbsa.csv")
# print(correlation_table)

## Scope 2

In [13]:
cols = ['res_tc',
 'com_tc',
 'ind_tc',
 'p_wrkage',
 'pct_ao0',
 'pct_ao1',
 'pct_ao2p',
 'r_pctlowwa',
 'totemp',
 'totpop',
 'e5_ret',
 'e5_off',
 'e5_ind',
 'e5_svc',
 'e5_ent',
 'e8_ret',
 'e8_off',
 'e8_ind',
 'e8_svc',
 'e8_ent',
 'e8_ed',
 'e8_hlth',
 'e8_pub',
 'e_pctlowwa',
 'd1a',
 'd1b',
 'd1c',
 'd1c5_ret',
 'd1c5_off',
 'd1c5_ind',
 'd1c5_svc',
 'd1c5_ent',
 'd1c8_ret',
 'd1c8_off',
 'd1c8_ind',
 'd1c8_svc',
 'd1c8_ent',
 'd1c8_ed',
 'd1c8_hlth',
 'd1c8_pub',
 'd1d',
 'd2a_jphh',
 'd2b_e5mix',
 'd2b_e5mixa',
 'd2b_e8mix',
 'd2b_e8mixa',
 'd2a_ephhm',
 'd2c_trpmx1',
 'd2c_trpmx2',
 'd2c_tripeq',
 'd2r_jobpop',
 'd2r_wrkemp',
 'd2a_wrkemp',
 'd2c_wremlx',
 'd3a',
 'd3aao',
 'd3amm',
 'd3apo',
 'd3b',
 'd3bao',
 'd3bmm3',
 'd3bmm4',
 'd3bpo3',
 'd3bpo4',
 'd4a',
 'd4b025',
 'd4b050',
 'd4c',
 'd4d',
 'd4e',
 'd5ar',
 'd5ae',
 'd5br',
 'd5be',
 'd5cr',
 'd5cri',
 'd5ce',
 'd5cei',
 'd5dr',
 'd5dri',
 'd5de',
 'd5dei',
 'd2a_ranked',
 'd2b_ranked',
 'd3b_ranked',
 'd4a_ranked',
 'natwalkind',
 'w_p_lowwag',
 'w_p_medwag',
 'w_p_highwa',
 'gasprice',
 'c_r_white',
 'c_r_male',
 'c_r_lowwag',
 'c_r_medwag',
 'c_r_highwa',
 'c_r_drmv',
 'p_highschool',
 'p_owner',
 'avg_hh_size',
 'med_dwelling_age'
]

rows_keep = ['res_tc',
 'com_tc',
 'ind_tc',            
 'd1a',
 'd1b',
 'd1c',
 'd1c5_ret',
 'd1c5_off',
 'd1c5_ind',
 'd1c5_svc',
 'd1c5_ent',
 'd1c8_ret',
 'd1c8_off',
 'd1c8_ind',
 'd1c8_svc',
 'd1c8_ent',
 'd1c8_ed',
 'd1c8_hlth',
 'd1c8_pub',
 'd1d',
 'd2a_jphh',
 'd2b_e5mix',
 'd2b_e5mixa',
 'd2b_e8mix',
 'd2b_e8mixa',
 'd2a_ephhm',
 'd2c_trpmx1',
 'd2c_trpmx2',
 'd2c_tripeq',
 'd2r_jobpop',
 'd2r_wrkemp',
 'd2a_wrkemp',
 'd2c_wremlx',
 'd3a',
 'd3aao',
 'd3amm',
 'd3apo',
 'd3b',
 'd3bao',
 'd3bmm3',
 'd3bmm4',
 'd3bpo3',
 'd3bpo4',
 'd4a',
 'd4b025',
 'd4b050',
 'd4c',
 'd4d',
 'd4e',
 'd5ar',
 'd5ae',
 'd5br',
 'd5be',
 'd5cr',
 'd5cri',
 'd5ce',
 'd5cei',
 'd5dr',
 'd5dri',
 'd5de',
 'd5dei',
 'd2a_ranked',
 'd2b_ranked',
 'd3b_ranked',
 'd4a_ranked',
 'natwalkind',
]

df = gpd.read_parquet(elec_par_file)
df[rows_keep] = df.loc[:, rows_keep].replace(0, 1)
df.loc[:,rows_keep] = np.log(df.loc[:,rows_keep])

correlation_table = df.loc[:, cols].corr()
correlation_table = correlation_table.loc[rows_keep, cols_keep]
correlation_table.to_csv("/work/hawkins_lab/vulcan/results/correlation_table_elec.csv")
print(correlation_table)

/global/software/python/3.12.5/lib/python3.12/site-packages/pandas/core/internals/blocks.py:366: RuntimeWarning: invalid value encountered in log
  result = func(self.values, **kwargs)

            p_wrkage   pct_ao0   pct_ao1  pct_ao2p  r_pctlowwa    totemp  \
res_tc     -0.053093 -0.258345 -0.057635  0.258437    0.008026  0.088814
com_tc     -0.009043 -0.059175  0.104890 -0.026181    0.122580  0.339272
ind_tc     -0.032370 -0.160609 -0.036954  0.139056    0.050112  0.254206
d1a         0.202784  0.392143  0.332641 -0.475165   -0.082181  0.012256
d1b         0.206656  0.363431  0.276340 -0.417301   -0.098624  0.007804
...              ...       ...       ...       ...         ...       ...
d2a_ranked  0.023218  0.013006  0.052895 -0.023913   -0.001494  0.187868
d2b_ranked  0.054891 -0.041553  0.012101  0.048675   -0.126823  0.072812
d3b_ranked  0.150838  0.190266  0.315367 -0.328430   -0.018761  0.052018
d4a_ranked  0.201305  0.327874  0.248841 -0.378544   -0.059733  0.061416
natwalkind  0.197013  0.304848  0.323339 -0.398928   -0.037995  0.118247

              totpop    e5_ret    e5_off    e5_ind  ...  c_r_white  c_r_male  \
res_tc      0.435166  0.099336  0.036646  0.058359  ...   0.175803  0.085901
com_tc      0.176216  0.320419  0.162242  0.264645  ...   0.152450  0.060053
ind_tc      0.146966  0.201623  0.114218  0.310486  ...   0.284760  0.093918
d1a         0.036961  0.017656  0.029519 -0.088962  ...  -0.450500 -0.282013
d1b         0.090736  0.012186  0.022093 -0.087242  ...  -0.475116 -0.273367
...              ...       ...       ...       ...  ...        ...       ...
d2a_ranked -0.009969  0.259462  0.091176  0.147300  ...   0.083979  0.048353
d2b_ranked  0.185608  0.173213  0.056992  0.000787  ...   0.066565  0.023861
d3b_ranked -0.000199  0.063840  0.040192 -0.053244  ...  -0.351348 -0.194415
d4a_ranked -0.066059  0.037028  0.050646 -0.013648  ...  -0.447657 -0.203046
natwalkind -0.009437  0.150784  0.080081 -0.006145  ...  -0.386961 -0.191475

            c_r_lowwag  c_r_medwag  c_r_highwa  c_r_drmv  p_highschool  \
res_tc        0.204177    0.251600   -0.255115 -0.331236     -0.090582
com_tc        0.192417    0.151420   -0.180062 -0.258491      0.051350
ind_tc        0.155330    0.110911   -0.137406 -0.315836      0.074891
d1a          -0.352864   -0.335390    0.372746  0.521891     -0.159985
d1b          -0.377225   -0.351788    0.393723  0.532088     -0.145093
...                ...         ...         ...       ...           ...
d2a_ranked    0.035735   -0.023270    0.002240 -0.087583     -0.041610
d2b_ranked   -0.052336   -0.083843    0.079029 -0.052043     -0.176982
d3b_ranked   -0.273437   -0.260319    0.289335  0.313387     -0.134511
d4a_ranked   -0.310645   -0.268090    0.308487  0.445521     -0.056807
natwalkind   -0.290083   -0.300787    0.323537  0.379031     -0.135037

             p_owner  avg_hh_size  med_dwelling_age
res_tc      0.222158    -0.110801         -0.415165
com_tc     -0.090213    -0.171447         -0.147327
ind_tc      0.097208    -0.117114         -0.143786
d1a        -0.463074     0.013832          0.222810
d1b        -0.443033     0.123307          0.213238
...              ...          ...               ...
d2a_ranked -0.083728    -0.099766          0.020499
d2b_ranked -0.009624    -0.092898         -0.061763
d3b_ranked -0.354441     0.040399          0.252526
d4a_ranked -0.387355     0.063800          0.257175
natwalkind -0.435924     0.003971          0.281247

[66 rows x 35 columns]

In [14]:
# df_cbsa = df.groupby('cbsa').agg(aggregation_functions)
# correlation_table = df_cbsa.corr()
# correlation_table = correlation_table.loc[rows_keep, cols_keep]
# correlation_table.to_csv("/work/hawkins_lab/vulcan/results/correlation_table_elec_cbsa.csv")
# print(correlation_table)